### ISSUE TITLE
Mainnet

### ISSUE THREAD

**Issue by marcoarroyo41** [tinitodev/cardano-dapp-react-starter#1]
Hello. First of all thank you so much for this! 

How would you remove the testnet only functionality and allow this to work with main net wallets?

thanks again!

**Comment by tinitodev** [comment]
Hey @marcoarroyo41 you can try just removing this check here https://github.com/tinitodev/cardano-dapp-react-starter/blob/816b4f819f0c6f307428444c16175e06046f0730/src/context/WalletAPI/WalletAPIProvider.tsx#L40 where 'networkId' is 0 for Testnet and 1 for Mainnet, just call 'getAddress()' in both cases.. let me know if that's enough for your use-case or if you encounter any other issue.. Cheers!
